/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as donateSol from "./Donate.sol";
export type { donateSol };
export type { MockUSDC } from "./MockUSDC";
export * as factories from "./factories";
export type { CharityPoolWithVolatilityProtection } from "./Donate.sol/CharityPoolWithVolatilityProtection";
export { CharityPoolWithVolatilityProtection__factory } from "./factories/Donate.sol/CharityPoolWithVolatilityProtection__factory";
export { MockUSDC__factory } from "./factories/MockUSDC__factory";
