/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CharityPoolWithVolatilityProtection__factory } from "./CharityPoolWithVolatilityProtection__factory";
